=== RobFeng-Quest/TestDotNetException/ExportedXML/Command.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Command" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Command">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ProjectID CommandName " primary="yes" unique="yes" clustered="no" order="asc asc"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ProjectID" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="CommandName" minOccurs="1" od:jetType="memo" od:sqlSType="ntext" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Module" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="MultipleData" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="DataTableID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== RobFeng-Quest/TestDotNetException/ExportedXML/Command.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Command.xsd" generated="2017-04-26T15:17:54">
<Command>
<ProjectID>1</ProjectID>
<CommandName>Get_FileProductVersion</CommandName>
<Module>File</Module>
<Description></Description>
<MultipleData>0</MultipleData>
<DataTableID>3</DataTableID>
</Command>
<Command>
<ProjectID>1</ProjectID>
<CommandName>SilentInstall_MSI</CommandName>
<Module>Install</Module>
<Description></Description>
<MultipleData>1</MultipleData>
<DataTableID>1</DataTableID>
</Command>
<Command>
<ProjectID>1</ProjectID>
<CommandName>VerifyDllCopyRightAndDigSign_UnderFolder</CommandName>
<Module>File</Module>
<Description></Description>
<MultipleData>1</MultipleData>
<DataTableID>4</DataTableID>
</Command>
<Command>
<ProjectID>1</ProjectID>
<CommandName>VerifyFileProperties</CommandName>
<Module>File</Module>
<Description></Description>
<MultipleData>1</MultipleData>
<DataTableID>2</DataTableID>
</Command>
</dataroot>
